In [1]:
#Numpy
# ->numerical python or numeric python.
# ->numpy is a programming language that deals with multi-dimensional arrays and matrices.
# ->numpy supports a large number of mathematical operations.

##why use numpy
# ->numpy is memory efficiency meaning it can handle the vast amount of data more accessible than any other library.
# ->especially for matrix multiplication and reshaping.
# ->on top of that.Numpy is fast,infact,tensorflow and scikit.

In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.18.5


In [5]:
#one dimensional array
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [6]:
print(np.array([2,4,6,8]))

[2 4 6 8]


In [11]:
#two dimensional data
#have to take 2 lists with in single one
data=np.array([[1,2,3,4],[5,6,7,8]])
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
#mathematical operations
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1%a2)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[1 2 3 4]


In [19]:
#shape 
data=np.array([[1,2,3,4],[5,6,7,8]])
print(np.shape(data))
print(data.dtype)


(2, 4)
int32


In [22]:
data=np.array([[1.2,3.4,5.6,1.4],[2.3,5.8,6.9,3.5]])
print(np.shape(data))
print(data.dtype)

(2, 4)
float64


In [29]:
#numpy zeroes and ones
#numpy zeroes
np.zeros((3,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [34]:
#reshape
data=np.array([[1,2,3],[4,5,6]])
print(data)
data.reshape((3,2))

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
#numpy flatten
print(data)
data.flatten()

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [36]:
#numpy hstack->data horizontal append
print(a1)
print(a2)
np.hstack((a1,a2))

[1 2 3 4]
[5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
#vstack
print(a1)
print(a2)
np.vstack((a1,a2))

[1 2 3 4]
[5 6 7 8]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
#vstack single variable
print(a1)
np.vstack((a1))

[1 2 3 4]


array([[1],
       [2],
       [3],
       [4]])

In [40]:
#hstack single variable
print(a2)
np.hstack((a2))

[5 6 7 8]


array([5, 6, 7, 8])

In [42]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,4,5],[3,5,8]])
print(np.hstack((a,b)))

[[1 2 3 2 4 5]
 [4 5 6 3 5 8]]


In [52]:
#to calculate mean,median,mod->avg(mean)
print(data)
data.mean()
print(np.median(data))
print(np.mod(2,3))

[[1 2 3]
 [4 5 6]]
3.5
2


In [45]:
#std deviation->sigma..
data.std()

1.707825127659933

In [57]:
#generate random numbers
d=np.random.randint(1,50,(3,3))


In [58]:
d

array([[36, 13, 20],
       [ 1,  4, 44],
       [11, 45, 29]])

In [65]:
#syntax:np.random.normal(loc(mean),scale(std),size)
np.random.randint(5,size=10)

array([0, 1, 3, 4, 0, 3, 1, 1, 1, 0])

In [59]:
np.random.normal(5,2,10)

array([2.32377655, 5.43330163, 7.02121   , 5.37619528, 2.35066742,
       3.17553642, 5.92592271, 2.89405551, 4.2968138 , 3.79348684])

In [60]:
#numpy statistical functions(max,min,mean,std)
d.mean()

22.555555555555557

In [62]:
d.min()


1

In [63]:
d.max()


45

In [64]:
d.std()

15.727619803751553

In [72]:
#transpose
print(d)
d.T

[[36 13 20]
 [ 1  4 44]
 [11 45 29]]


array([[36,  1, 11],
       [13,  4, 45],
       [20, 44, 29]])

In [74]:
#3 rows 3 columns
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
np.eye(4,dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
#dot
print(a1)
print(a2)
a1.dot(a2)

[1 2 3 4]
[5 6 7 8]


70

In [85]:
#pow
d=np.array([1,2,3,4])
np.array([d,pow(d,2)])

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [92]:
#repeat
a=np.repeat([1,2,3,4],3)

In [87]:
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [103]:
#arange
#syntax:arange(start,stop,stepcount)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [105]:
#fact program using numpy
a=np.math.factorial(5)
a

120

In [108]:
#linspace(default=50)
#syntax:linspace(start,stop,num,endpoint)
np.linspace(1,2,num=10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [117]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [120]:
x=np.array([[1,2,3],[4,5,6]])
x


array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
x[0]

array([1, 2, 3])

In [122]:
x[1]

array([4, 5, 6])

In [129]:
print(x)
x[:,1]

[[1 2 3]
 [4 5 6]]


array([2, 5])